server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.130:28999
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
          lower-case-service-id: true
      routes:  # 路由
        - id: user-provider #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://user # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/api/user/** # 断言，路径相匹配进行路由
